### ISSUE TITLE
Finalize membership of TSC

### ISSUE THREAD

**Issue by dstebila** [pq-code-package/tsc#1]

**Comment by planetf1** [comment]
To continue the steps to form the TSC, we could start off with the maintainers of the initial implementations we discussed during PQCA formation, and set up during the recent Hackathon:

| repo | maintainer |
| -- | -- |
| mlkem-c-aarch64<br>mlkem-c-embedded | @mkannwischer |
| mlkem-c-generic | @jschanck |
| mlkem-libjade | @mbbarbosa |
| mlkem-libcrux | @franziskuskiefer |

Plus @dstebila as one of the founders of pqcp & oqs lead. I'll volunteer also to try and get us up and running.

Anyone else I missed that's interested for the pre-TSC bootstrap?

For those mentioned so far:
 - would you be amenable to helping get the TSC off the ground? 
 - are you the right person or should it be someone else in your group?
 - are you ok with being in the first set of implementations we try and get fully onboarded, active, packaged up within pqcp?

We'll get help from the LF to put together an initial charter (#42) and need to get this reviewed. This will be discussed in the upcoming PQCA tac meetings

After this bootstrap process we will be able to revisit membership, voting, responsibilities, processes,  etc, but it will be good to get something started.

**Comment by franziskuskiefer** [comment]
👍🏻  sounds good to me

**Comment by mkannwischer** [comment]
Sounds good to me, too. Let me know how I can help.

**Comment by planetf1** [comment]
@mbbarbosa is also interested.
