### ISSUE TITLE
Schedule a remote hack day

### ISSUE THREAD

**Issue by dstebila** [pq-code-package/tsc#10]

**Comment by Sophrinix** [comment]
Has there been any movement on this task?

**Comment by dstebila** [comment]
Please let me know your availability for a PQ Code Package virtual hack day in late February/early March by filling out the following poll, no later than Wednesday February 21.  
	https://whenisgood.net/4rgb8mj

I don't know the exact format of the virtual hack day as I've never organized one of these before (if you have, please get in touch!  help very welcome) but at this point assume it will be an open session throughout that day where you can drop in when you are available from whatever time zone you're in.  More details to follow.

**Comment by dstebila** [comment]
Based on feedback I've received, it sounds like Tuesday March 12 would be a good day for a virtual hack day for the PQ Code Package.  So please try to reserve some time on your calendar for that day.

I'm still trying to work out details of the format, but we'll likely have a voice & text channel open somewhere for people to drop in, discuss, and collaborate.  I'll send more information shortly about logistics.

I'm aware of people likely to be able to attend between the following times but, there may be people around before / after these times too.
	between 13:30 UTC / 14:30 Central European / 09:30 US Eastern / 06:30 US Pacific
	and 21:00 UTC / 22:00 Central European / 17:00 US Eastern / 14:00 US Pacific

**Comment by planetf1** [comment]
My understanding is that one aim of our Mar 12 session (~1330 UTC - 2100 UTC )  is to start getting projects onboarded ie hands-on, so for this thread we will need to:

agree on what projects can be added under pq-code-package (or the process for deciding on the day)
I presume all those listed in https://pad.riseup.net/p/KyberCodePackagePlanning-keep are in scope, but not others
Agree any legal aspects (contributor license agreements for example), or other rules prior to starting to load code into a repo
License must be Apache-2.0 or MIT
Do we need a standard CLA ?
Any extra advice Hart?
Ensure at least one person present has sufficient github project access for repo management
Happy to help, as I'm familiar with this process, though I don't have access - or will you do this Doug?
Ensure we have a core set of attendees to cover the expected duration
I am available for all of the event except 1500-1600 UTC
 
With repos created, and highly dependent on the attendees and projects, we can continue to do any combination of:
Create/setup new github repos (or transfer existing) & groups as needed
Migrate code from existing repos
Get basic builds working
Add additional checks (tests, scans, ….)

We could start working on the higher level documentation for pq-code-package:
Document any decisions/best practices ie as we setup repos
Could start with simple github pages, perhaps moving to a tool like mkdocs (or justthedocs)
Caveat: we need content to document. A simple summary of each new repo would be a start. Ultimately automated… but start simple

A quick summary of the objective of this thread, and some useful links, could start off the github docs (pq-code-package/docs ?)

There's already a thread on discord about comms - I think we need zoom (sync/video) + discord (async/text)

Potentially there may be more in-depth technical discussions of code, algorithms but it would be great to get some tangible assets in github as an outcome from the event.

**Comment by ryjones** [comment]
This is a test, so you know, ignore it

**Comment by dstebila** [comment]
Chipping in on items where I can, but some will have to be answered by LF folks.

> agree on what projects can be added under pq-code-package (or the process for deciding on the day) I presume all those listed in https://pad.riseup.net/p/KyberCodePackagePlanning-keep are in scope, but not others 

Yes, I think there was consensus in our earlier calls about this group of projects.  Ultimately it will be the task of a TSC to decide which new implementations to start or accept, but for now I think the ones listed there (generic C, AVX2, Rust, Python, test vectors, stack optimized & 32-bit C, and aarch64) are what we should limit ourselves to in the initial hack day.

> Ensure at least one person present has sufficient github project access for repo management Happy to help, as I'm familiar with this process, though I don't have access - or will you do this Doug? 

I will try to be there as much as I can, but won't be there the whole time.  Currently only Ry and I have admin access on the PQCP Github org.  If we can identify the desired repository names in advance via #11 then we can create the relevant repos in advance. Or @ryjones should we add additional admins who can create these?

**Comment by ryjones** [comment]
@dstebila for now, I ask you not create repos by magic, but by filing an issue against the TSC repo saying what you want and how you want it. I will fill in more details later.

**Comment by planetf1** [comment]
We have a 'mini-site' at https://hackathon.pqcodepackage.org/ ([source](https://github.com/pq-code-package/pq-code-package-hackathon))

This aims to explain what the hackathon it is, where it is, and how people can contribute and get help.

It's really a bootstrap to starting to get our processes in place for future onboarding, so some of the hackathon may be doing some of the things we wish we had in place for this hackathon ....

Would really appreciate any feedback - especially with anything that's wrong or misleading - I think we should post this on appropriate channels in the next day or so. (I've already pointed the expected project owners at it)

**Comment by planetf1** [comment]
We had a successful day at the hackathon.

I'll aim to share a summary in the next couple of days

**Comment by planetf1** [comment]
Notes from session -> https://hackathon.pqcodepackage.org/202404/summary.html (source is in the hackathon repo - updates welcome)

**Comment by planetf1** [comment]
I think we can close this issue now (hope that's ok) as the first Hackathon was run, and there is a new issue #31 to track arranging the next hackathon
