### ISSUE TITLE
Archive mlkem-c-generic

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/tsc#111]
As discussed in the last TSC meeting from 2024-10-24, https://github.com/pq-code-package/mlkem-c-generic is to be superseded by https://github.com/pq-code-package/mlkem-c-aarch64/, which is to be renamed accordingly (see #105).

**Comment by hanno-becker** [comment]
@planetf1 Can you take care of this one?

**Comment by planetf1** [comment]
Yes I will do this

**Comment by planetf1** [comment]
* added readme
* closed existing issues/PRs
* archived

Once we've renamed the new repo we can update things like the main pq-code-package readme.
