### ISSUE TITLE
Repository request: mlkem-c-embedded

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/tsc#21]
I'd like to request the following PQCP repository:

**Name**: mlkem-c-embedded
**Description**: This library provides a MLKEM implementation optimized for embedded microcontrollers. The library will have both stack optimizations and speed optimizations for 32-bit platforms. The first goal is to take the state-of-the-art Cortex-M4 implementations (in [pqm4](https://github.com/mupq/pqm4) ) and turn them into portable production-grade Apache-2.0-licensed implementations. Where needed (inline-)assembly will be added to achieve best performance while keeping the generic portable implementations as an option. In the long term, the goal is to optimize for more 32-bit platforms. Obvious choices would be 32-bit RISC-V (e.g, [HiFive1](https://www.sifive.com/boards/hifive1-rev-b))  or any of Arm Cortex-M3, Arm Cortex-M7, Arm Cortex-M55, Arm Cortex-M85. It will depend on contributors which platforms will be considered.

**License**: ~MIT~ Apache-2.0
**Access**: 
 - Admin: @mkannwischer 
 - Maintainer: @mkannwischer 
 - Core contributors: @mkannwischer [@potsrevennil](https://github.com/potsrevennil)

**Existing code**: https://github.com/mupq/pqm4 based on https://github.com/pq-crystals/kyber/tree/standard (However, the license situation in pqm4 is not ideal, so I do expect that we'll have to reimplement certain parts to be able to license everything under Apache-2.0.)

**Call for contributors**: We are looking for co-maintainers and contributors to help drive this library forward. If you are interested, please reach out to me!

**Comment by mkannwischer** [comment]
Thanks @planetf1!

> 
> * Would your proposal change at all if the pq crystals kyber reference implementation were also onboarded (as we hope)? I'm thinking in terms of reuse?

No, not immediately. It makes sense to coordinate to possibly allow some code sharing in the future. But I'd see this as low priority.

> * How would you want to start the repository

We'd start with a copy of the Kyber reference implementation, add a buildsystem for the Cortex-M4 (e.g., the STM32F407G-DISC1), add some basic tests and benchmarks, and apply the stack and speed-optimizations using C for as much as possible.
The goal would be to have something functional by tomorrow night and a list of issues of the tasks left that we can work on over the coming weeks.

> * A full or partial repo move from pqm4 -- this will need more discussion. I think it comes down to whether you need/want/can preserve history. I'd err on keeping the new repo fresh.

No, it does not make sense to move the repo.
This is only going to be a very small part of pqm4, and I'd like to keep the licenses much cleaner than in pqm4.
This means we will have to rewrite quite a bit of code in there and at the same time will try to write portable code rather than M4-specific assembly whereever possible.

**Comment by planetf1** [comment]
Ok sounds good. Are you ok with the template or do you want an empty repo and then add the standard files later?

**Comment by mkannwischer** [comment]
The template looks good. Thanks!

**Comment by planetf1** [comment]
Repo is created https://github.com/pq-code-package/mlkem-c-embedded

Note - we ask that you use '--signoff' ie signoff commits.

**Comment by mkannwischer** [comment]
Thanks, @planetf1! Looking good!

**Comment by rpls** [comment]
I can definitely contribute to some smaller degree this year, mostly in the area of platform & build support. Next year I would have more time.

**Comment by planetf1** [comment]
Repo has been created.

We have teams
pqcp-embedded
pqcp-embedded-maintainers
pqcp-embedded-admin

I have made Matthias maintainer of each team

removed wikis & merge commits to match settings.yml
activated DCO for branch protection

Complete, so closing

**Comment by mkannwischer** [comment]
Thanks @planetf1! All working as we need it.

@rpls, thanks! Do you think you would have time to review pull requests this year? Right now we are still in the early stages of getting things up and running, but once we have the basic setup done, we should go for more thorough reviews. Your help would be greatly appreciated. If yes, I'll add you to the maintainers.

**Comment by rpls** [comment]
> Do you think you would have time to review pull requests this year?
@mkannwischer Yes. That and help with build system and platform support (e.g., code for MCU or boards).
