### ISSUE TITLE
Repository request: mlkem-rust-libcrux

### ISSUE THREAD

**Issue by franziskuskiefer** [pq-code-package/tsc#23]
I'm requesting the following PQCP repository:

**Name**: mlkem-rust-libcrux
**Description**: This library provides a portable ML-KEM implementation with some optimisations for AVX2. Full AVX2 support will be added over the coming months. The code is formally verified for panic freedom, correctness, and secret independence in [F*](https://www.fstar-lang.org/) using the [hax](https://github.com/hacspec/hax) toolchain.

**License**:  Apache-2.0

**Access**:
* Admin: @franziskuskiefer 
* Maintainer: @franziskuskiefer 
* Core contributors: @franziskuskiefer @karthikbhargavan 
 
**Existing code**: https://github.com/cryspen/libcrux/tree/main/src/kem

**Call for contributors**: We are looking for co-maintainers and contributors to help drive this library forward. If you are interested, please reach out to me!

**Comment by planetf1** [comment]
I'll start on creating the repository/users as part of the hackathon activity.

**Comment by planetf1** [comment]
Do you want to
 - start with the template (pq-code-package/template-code ?
 - start with a clean repo
 - move existing repo (history, more complex)
 
 I'll then setup the repo

**Comment by planetf1** [comment]
Repo created.

These teams were created
pqcp-libcrux (used for read access)
pqcp-libcrux-maintainers (used for maintain)
pqcp-lincrux-admin (used for admin)

I added Franzikskus as maintainer for each team

I also disabled wikis & merge commit as per settings.yml

Complete, so closing
