### ISSUE TITLE
Add MQuaresma to pqcp org

### ISSUE THREAD

**Issue by planetf1** [pq-code-package/tsc#27]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add: MQuaresma
* Project to be added to: libjade

Part of https://github.com/pq-code-package/tsc/issues/24

* [Team to be added to](https://github.com/orgs/pq-code-package/teams): pqcp-contributors, pqcp-libjade

**Comment by ryjones** [comment]
invite sent!
