### ISSUE TITLE
Repository request: mlkem-c-generic

### ISSUE THREAD

**Issue by jschanck** [pq-code-package/tsc#30]
* GitHub repo to create: mlkem-c-generic
* Project to be added to: pq code package
* People:
  * John Schanck, Peter Schwabe, Normal Ashley

**Comment by ryjones** [comment]
[https://github.com/pq-code-package/mlkem-c-embedded](https://github.com/pq-code-package/mlkem-c-embedded)

**Comment by planetf1** [comment]
> hi, I need a github ID for Normal Ashley @jschanck

@ashman-p

**Comment by planetf1** [comment]
@ryjones I think @mkannwischer should be removed from pqcp-generic-admin

**Comment by planetf1** [comment]
See #32 - I think the fix there in PR #36 would close this

**Comment by planetf1** [comment]
Closing, since the repo and access groups are created.
New issues can be raised for any corrections
