### ISSUE TITLE
Add rpls to GitHub

### ISSUE THREAD

**Issue by rpls** [pq-code-package/tsc#33]
As discussed in #21

Please include:

* GitHub ID to add: @rpls
* Project to be added to:  mlkem-c-embedded

One of:

* [Team to be added to](https://github.com/orgs/pq-code-package/teams):  `pqcp-embedded*`

**Comment by planetf1** [comment]
@mkannwischer has access to those groups and can add you. Any issues let me know and I'll sort out.
Once the TSC is informed we'll refine the exact process, it will hopefully via github tooling

**Comment by ryjones** [comment]
@rpls invite sent
