### ISSUE TITLE
Add someone to GitHub

### ISSUE THREAD

**Issue by planetf1** [pq-code-package/tsc#39]
If you want to be able to assign bugs to someone, they only need **Read** access.

Please include:

* GitHub ID to add:  hartm (to the organization)
* Project to be added to: tsc 

One of:

* [Team to be added to](https://github.com/orgs/pq-code-package/teams): pqcp-contributors, pqcp-tsc

We need to add @hartm to the pqcp organization so that he can advise on pqca/LF issues so org membership is crucial. (adding makes it more obvious/easier to mention) I think it would make sense to have read access to the tsc also

**Comment by ryjones** [comment]
Hi - please file a PR against https://github.com/pq-code-package/tsc/blob/main/access-control.yaml
