### ISSUE TITLE
Agree charter for the pq-code-package project

### ISSUE THREAD

**Issue by planetf1** [pq-code-package/tsc#42]
We need to draft, review & agree a charter for the pq-code-package project.

The Linux Foundation will help create the initial draft.

See also #1 for gathering early draft reviews

**Comment by hartm** [comment]
@planetf1 Yes, can you also give me code repositories you want to include that I can point to?  Thanks!

**Comment by planetf1** [comment]
We can use the current list, but can you just clarify the context? And what info you need?

This is for the pq-code-package project. We have the following crypto implementation repositories (though not all are populated yet)

These have active code:
- mlkem-c-embedded
- mlkem-c-aarch64

These are setup, have been discussed, and have PRs outstanding to merge implementations in (I'm chasing)
- mlkem-c-generic
- mlkem-libjade

These only have template code, no contributions yet :-(
- mlkem-rust-libcrux

We also have a few utility repos:
- tsc (for tracking, processes)
- documentation (technical & process docs - currently a skeleton)
- pq-code-package-hackathon (to support hackathons)
- template-code (for setting up new repos)
- .github (simple bootstrap docs)

**Comment by hartm** [comment]
Thanks, that's really useful!  I'm just trying to get more info for the formation team so that they can get an accurate scope of the project.

**Comment by hartm** [comment]
We already have a charter, it seems:  https://github.com/pq-code-package/tsc/blob/main/charter/charter-2024-01-29.pdf. Thanks to the formation team for pointing this out.

**Comment by planetf1** [comment]
Thanks. We'll take this as the active charter, and any issues/queries will put through the defined process. Thanks for confirming - I should have noticed it!
