### ISSUE TITLE
Arrange TSC kickoff meeting

### ISSUE THREAD

**Issue by planetf1** [pq-code-package/tsc#44]
We now have a proposed list of initial TSC members in #1

A kickoff meeting now needs to be arranged.

Please can all initial TSC members review and comment on the:
* [proposed agenda ](https://github.com/pq-code-package/tsc/pull/43)
* [suitable days/times](https://www.when2meet.com/?24641314-158Zj)

Once we have the kickoff we can iterate on this to get sorted on an ongoing basis

@mbbarbosa @mkannwischer @dstebila @franziskuskiefer 
Also fyi @hartm @ryjones interested in your feedback from how other TSCs have launched.

**Comment by planetf1** [comment]
fyi @tfaoliveira

**Comment by planetf1** [comment]
fyi @jschanck

**Comment by planetf1** [comment]
| Participant|Location|Timezone (summer)|
| -- | -- | -- |
| @mbbarbosa | Portugal | UTC+1 |
| @mkannwischer | Taiwan | UTC+8 |
| @dstebila | Canada / Ontario | UTC-4 | 
| @franziskuskiefer | Germany | UTC+2 | 
| @hartm | USA / California | UTC-7 | 
| @ryjones | USA / Washington | UTC-7 |
| @tfaoliveira | Portugal | UTC+1 |
| @planetf1 | UK | UTC+1 |
| @jschanck | Canada / Ontario | UTC-4 |

Timezone Spread: **15 hours**
Timezone spread without LF: **12 hours**

**Comment by tfaoliveira** [comment]
I just filled in my availability here [suitable days/times](https://www.when2meet.com/?24641314-158Zj), from [here](https://github.com/pq-code-package/tsc/issues/44#issue-2245871196). I might be able to adjust my availability if needed.

**Comment by dstebila** [comment]
Is the when2meet showing things in my time zone or in UTC? For example right now I see that Nigel's availability on Mondays starts at 0900, which is probably in his time zone? or UTC? I want to make sure I'm answering in the right time zone.

**Comment by planetf1** [comment]
@dstebila I should have been clearer - I was expecting the answer in local timezone for you. My responses were a first pass but I have flexibility to accomodate (though we are mid ca/tw in any case)

@mkannwischer is good to 2100, perhaps 2200 - not fridays

2100 Taiwan / 0900 Ontario CA / 1400 UK / 1500 Portugal/Germany / 0700 US pacific

Thursday is clearest from the availability (of 2 responses..)

So we could aim for **Thu 2 May @ 1300 UTC** ? Would that work?

If not, one hour later?
If not - 1300 on tue/thu, but that makes it earlier in us/canada

**Comment by mkannwischer** [comment]
I cannot join Thu 2 May or Fri 3 May, sorry. The week after would be easier for me.

**Comment by dstebila** [comment]
> 2100 Taiwan / 0900 Ontario CA / 1400 UK / 1500 Portugal/Germany / 0700 US pacific
> 
> Thursday is clearest from the availability (of 2 responses..)
> 
> So we could aim for **Thu 2 May @ 1300 UTC** ? Would that work?
> 
> If not, one hour later? If not - 1300 on tue/thu, but that makes it earlier in us/canada

Thursdays at 1300 UTC is fine for me on May 2 and on a recurring basis in general.

**Comment by mbbarbosa** [comment]
Hey, PT is on the same time zone as UK and this slot works for me as well.

**Comment by franziskuskiefer** [comment]
13:00 UTC on Thursday works for me in general. I have something at 13:30 every other week.

**Comment by planetf1** [comment]
I would suggest May 9 to allow @mkannwischer to join, but it was pointed out on the PQCA TAC that we have the RSA conference May 6-9. Are any of our proposed members attending this?

**Comment by dstebila** [comment]
> I would suggest May 9 to allow @mkannwischer to join, but it was pointed out on the PQCA TAC that we have the RSA conference May 6-9. Are any of our proposed members attending this?

I'm not attending RSA and remain available on May 9.

**Comment by franziskuskiefer** [comment]
I'm not at RSA but May 9th is a public holiday over here. I should be able to make it though.

**Comment by mbbarbosa** [comment]
Same here.

**Comment by planetf1** [comment]
Let's go for May 9 @1300 UTC. I'll contact Naomi to get the meeting invite set up

**Comment by Naomi-Wash** [comment]
Hello everyone! I've sent the meeting invite to the PQCP mailing list and will also announce in Discord. 
Please let me know if you did not receive the invite. A few of you were not included in the mailing list, so please be sure to join here: https://lists.pqca.org/g/pq-code-package-tsc

**Comment by planetf1** [comment]
Closing as this was held
