### ISSUE TITLE
PQCP TSC Chair Election 2024

### ISSUE THREAD

**Issue by Naomi-Wash** [pq-code-package/tsc#52]
# The PQCP TSC Chair position is open for election. 

Pursuant to the PQCP [Technical Charter](https://github.com/pq-code-package/tsc/blob/main/charter/charter-2024-01-29.pdf) (2.f.), 

> The TSC may elect a TSC Chair, who will preside over meetings of the TSC and will serve until their resignation or replacement by the TSC. The TSC Chair, or any other TSC member so designated by the TSC, will serve as the primary communication contact between the Project and Post-Quantum Cryptography Alliance.

## Nomination Period
Thursday, May 9 - Thursday, May 16, 2024

### Submit nominations to this GH Issue

Include: 
1. Name
2. Company
3. Brief background
4. Why you are a good fit for the role

## Voting Period
Friday, May 17 - Wednesday, May 22, 2024
 
If 2 or more nominations are submitted, execute a rank-based vote.

**Comment by planetf1** [comment]
Nominee: **Nigel Jones**
Company Affiliation: **IBM**

I'm a software engineer at IBM Quantum and have been working in opensource development for the last 8 years, including with Linux Foundation projects (and more years before this on proprietary/consuming). 

I started in Quantum-safe crypto mid 2023, and delivered education material on PQC before getting more closely involved in the PQCA including discussion prior to its formation, and join the PQCA TAC Meetings where I've started activites in workgroups. I'm also  engaged in open quantum safe activities, regularly attending the TSC and development calls. For pqcp I arranged the first hackathon and TSC meeting.

If elected I will continue to support the pqcp community, help drive the project forward to make quantum-safe more reachable for the community, work closely with our colleagues in these other teams, support logistical aspects, and contribute with software engineering expertise/coding - trying to identify opportunities and fill in gaps.

**Comment by Naomi-Wash** [comment]
I am pleased to announce the results of the PQ Code Package TSC Chair election. We had an equal number of nominations for the seats available, so the nominee was automatically elected.

Congratulations Nigel, your term is from May 2024 - April 2025.
