### ISSUE TITLE
TSC - ongoing meeting schedule

### ISSUE THREAD

**Issue by planetf1** [pq-code-package/tsc#60]
In our [TSC meeting on 2024-05-23](https://github.com/pq-code-package/tsc/pull/59) we agreed to review the current meeting schedule.

**Note that the next meeting will follow the current pattern, and will be on 2024-06-06 at 13:00 UTC.**

Currently we are arranging 1-off meetings on alternate Thursdays at 1300 UTC [as agreed for the first meeting](https://github.com/pq-code-package/tsc/issues/44)

This is fairly late (2100) for Taiwan, and very early for US, particularly west-coast (0600)

TSC participants so far are spread as follows:

| Participant|Voting Member|Location|Timezone (summer)|
| -- | -- | -- | -- |
| @ajbozarth  |  | US / Texas | UTC-5 |
| @ashman-p  |  |  |  |
| @dstebila | Y | Canada / Ontario | UTC-4 | 
| @franziskuskiefer | Y | Germany | UTC+2 | 
| @hanno-becker  | Y | | UTC+1 |
| @hartm |  | USA / California | UTC-7 | 
| @jschanck | Y | Canada / Ontario | UTC-4 |
| @mbbarbosa | Y | Portugal | UTC+1 |
| @mkannwischer | Y| Taiwan | UTC+8 |
| @planetf1 | Y | UK | UTC+1 |
| @ryjones |  | USA / Washington | UTC-7 |
| @tfaoliveira | Y | Portugal | UTC+1 |
| Duc Tri Nguyen | | US / VI | UTC-4 |
| Michael Maximilien |  | US / California| UTC-7 |
| Rod Chapman |  | UK | UTC+1 |
| Yarkin Doroz | | US / MA | UTC-4 |

Timezone Spread: **15 hours**
Timezone spread of voting members: **12 hours**

**Comment by planetf1** [comment]
Please comment with your thoughts below.

A few things to consider

*Frequency*:

* We've had 2 meetings close together, but ran out of time in both. There seems plenty to discuss, and we're making progress. We don't yet have other formal meetings, so continuing alternate weeks could be useful.

*time*:

* 1300 UTC is very early for US west coast (0600). just one hour later 1400 UTC could help but is very late in Taiwan?
* some groups have alternating times to encourage the broadest participation, but at the risk of fragmentation. This could allow for any of the following
 - Europe/Asia
 - Europe/North America
 - Asia/North America 
 
 *day*:
 
 Thursday seems to work well at the current time, but may need to change if we modify time. Excluding Monday/Friday probably makes sense to avoid pushing working week boundaries.

**Comment by hanno-becker** [comment]
Minor correction (with no impact): I'm UK time, so UTC+1.

**Comment by planetf1** [comment]
> Minor correction (with no impact): I'm UK time, so UTC+1.

Ah thanks. I didn't realise! Table updated with timezone

**Comment by planetf1** [comment]
As discussed in 2024-06-20 TSC meeting we will close this until someone brings up the issue again and we can establish an updated consensus on timing/schedule.
