### ISSUE TITLE
Access to AWS AArch64 runners

### ISSUE THREAD

**Issue by hanno-becker** [pq-code-package/tsc#75]
Relates to: #55 

AWS Graviton2 and Graviton3 instances are among the current benchmarking targets for MLKEM-C-AArch64 (see [README](https://github.com/pq-code-package/mlkem-c-aarch64) for the others, though note this list may still evolve).

The purpose of this issue is to track if/how we could provide access to AWS Graviton-based runners for MLKEM-C-AArch64 in particular, or the PQCP the general.

**Comment by hanno-becker** [comment]
Tagging @ry who has done some initial investigation here.

**Comment by ryjones** [comment]
Hi,
I have the AWS account and credit card; I need someone to work with me on setting up the IAM roles etc.

[I plan to use this action](https://github.com/marketplace/actions/on-demand-self-hosted-aws-ec2-runner-for-github-actions) but I am a newbie when it comes to setting up AWS accounts.

**Comment by planetf1** [comment]
@hanno-becker I believe this is now complete and setup for aarch64 as per the update in the last TSC.?

**Comment by hanno-becker** [comment]
@planetf1 Yes!
